site_name: blackscholes
theme:
  name: material
  palette:
    primary: black
    accent: cyan
  font:
    text: Ubuntu
  icon:
    logo: material/library-shelves
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.expand
markdown_extensions:
  - footnotes
  - codehilite:
      linennums: true

plugins:
  - mkdocstrings
